Update version to snapshot
bcgov/jag-file-submission pull request #1045
Opened 2020-11-05 21:50 UTC by TayGov

# Description

This PR includes the following proposed change(s):

Version update

2020-11-05 22:04 UTC, akroon3r submitted a review, later dismissed

2020-11-05 22:04 UTC, akroon3r commented
🐦

2020-11-06 15:06 UTC, alexjoybc requested changes
0.5.0-SNAPSHOT lol my fault and also we need to update the package.json in both front end

2020-11-06 15:16 UTC, alexjoybc approved these changes

2020-11-06 16:03 UTC, merged