Rush validation
bcgov/jag-file-submission pull request #2252
Opened 2021-09-13 13:15 UTC by yousiefc

# Description

This PR includes the following proposed change(s):

- Rush now redirects correctly
- Rush data now submitted on continue
- Prepopulation issue resolved

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Refactoring / Documentation
- [ ] Version change

if your change is a breaking change, please add `breaking change` label to this PR

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes.

## Does the change impact or break the Docker build?

- [ ] Yes
- [x] No

If Yes: Has Docker been updated accordingly?

- [ ] Yes
- [x] No

## Checklist:

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [ ] I have made corresponding changes to the documentation
- [x] New and existing unit tests pass locally with my changes

2021-11-29 17:43 UTC, BrendanBeachBC submitted a review, later dismissed
Looks good! One question related to a change that I made to the rush page recently

2021-11-29 17:43 UTC, BrendanBeachBC commented on src/frontend/efiling-frontend/src/components/page/rush/Rush.js
> +      country: fields.country,
During the phone number validation fix, I switched country from being a string to being an object with code and description fields. Does this need to be switched to be `fields.country.description` or does the rush submission work with the object?

2021-11-30 18:31 UTC, TayGov requested changes
Just the one thing about the radio buttons

2021-11-30 18:31 UTC, TayGov commented on src/frontend/efiling-frontend/src/components/page/rush/Rush.js
> +            resetFields();
This should be re-ordered from:
setFields({ ...fields, rushType: "rule" });
setRadio1(true);
resetFields();

To:
resetFields();
setFields({ ...fields, rushType: "rule" });
setRadio1(true);

The reset is actually clearing the rushType. This applies to all three radio buttons.

2021-12-01 15:55 UTC, TayGov approved these changes
👍

2021-12-01 15:58 UTC, merged